[package]
authors = ["Jan Walter <jan@janwalter.com>"]
edition = "2018"
name = "rs_pbrt"
version = "0.9.2"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/wahn/rs_pbrt"
documentation = "https://www.rs-pbrt.org/doc/crates/rs_pbrt/index.html"
description = "Physically based rendering (PBR) with Rust"
homepage = "https://www.rs-pbrt.org"
[dependencies]
atom = "0.4.0"
atomic = "0.5.0"
byteorder = "1.4.3"
crossbeam = "0.8.0"
crossbeam-channel = "0.5.1"
hexf = "0.2.1"
image = "0.23.14"
impl_ops = "0.1.1"
lazy_static = "1.4.0"
num = "0.4.0"
num_cpus = "1.13.0"
pbr = "1.0.4"
pest = "2.1.3"
pest_derive = "2.1.0"
ply-rs = "0.1.3"
rayon = "1.5.0"
smallvec = "1.6.1"
structopt = "0.3.21"
strum = "0.21.0"
strum_macros = "0.21.1"
typed-arena = "2.0.1"
nalgebra = {version ="0.26.2" }
nalgebra-glm = "0.12.0"
rand = "0.8.3"
statrs = "0.14.0"
[[bin]]
name = "rs_pbrt"
path = "src/bin/rs_pbrt.rs"
